In [1]:
import pandas as pd

In [2]:
res = pd.read_csv("../criteo_sample.txt")

In [3]:
res1 = res.loc[5:25,['C1','C2','C3','I1','I2']]

In [4]:
f1 = res1.reset_index(drop=True)

In [5]:
f1

          C1        C2        C3    I1   I2
0   68fd1e64  207b2d81  9dd3c4fc   0.0   -1
1   05db9164  2a69d406  fcae8bfa   0.0  370
2   05db9164  403ea497  2cbec47f  19.0   10
3   8cf07265  0aadb108  c798ded6   0.0    0
4   05db9164  58e67aaf  ea997bbe   2.0   11
5   05db9164  e77e5e6e  c23785fe   2.0    1
6   05db9164  d7988e72  25111132   NaN    2
7   05db9164  ed7b1c58  b063fe4e   0.0    5
8   68fd1e64  38a947a1       NaN   8.0   -1
9   5bfa8ab5  84b4e42f  45f68c2a   0.0    0
10  05db9164  38d50e09  5d0ec1e8   NaN   82
11  5a9ed9b0  68b3edbf  b00d1501   NaN   24
12  05db9164  38d50e09  fc1cad4b   NaN  105
13  9a89b36c  1cfdf714  9d427ddf   5.0   85
14  68fd1e64  2eb7b10e  378112d3   2.0    3
15  8cf07265  4f25e98b  a68b0bcf   NaN    1
16  05db9164  8947f767  6bbe880c   NaN    4
17  68fd1e64  38a947a1  dd8e6407   0.0    0
18  5a9ed9b0  46bbf321  c5d94b65   0.0   43
19  68fd1e64  38a947a1  98351ee6   0.0    1
20  5a9ed9b0  9819deea  6813d33b   9.0    1